<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta name="viewport" content="width=device-width" />
	<title>Botany Template</title>
	<meta name="keywords" content="botany, responsive, bootstrap, free template, fluid layout, templatemo, html css" />
	<meta name="description" content="Botany Template is free responsive template with a fluid background image." />
	<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="templatemo_style.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="flexslider.css" type="text/css" media="screen" />

	<!-- Modernizr -->
  	<script src="slider/modernizr.js"></script>

	<!-- HTML 5 shim for IE backwards compatibility -->
		<!-- [if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
		</script>
		<![endif]-->
	<!--
	Credits
	Equal Height Columns http://www.hongkiat.com/blog/css-equal-height/ -->
</head>
<body class="templatemo_juice_bg">
	<div id="main_container">
		<div class="container" id="home">
			<div class="row col-wrap">
				<div id="left_container" class="col col-md-3 col-sm-12">
                	<div class="templatemo_logo">
						<a rel="nofollow" href="http://www.templatemo.com/preview/templatemo_391_botany"><img src="images/templatemo_logo.png" alt="Botany Theme"></a>
					</div>
					<nav id="main_nav">
						<ul class="nav">
							<li class="active"><a href="#"><h6>Accueil</h6></a></li>
							<li><a href="http://localhost/projet/public/index/seconnecter"><h6>Se connecter</h6></a></li>
							<li><a href="contact.html"><h6>Contactez nous</h6></a></li>
							
						</ul>
					</nav> <!-- nav -->
					
				</div>
				<div id="right_container" class="col col-md-9 col-sm-12">

					<div class="row">
                    	<div class="col col-md-12">

                    		<h2>Welcome <a href="http://fr.onlyimage.com" title="images gratuites" class="right_container_title"  target="_blank">to</a> Botany</h2>

                            <div class="flexslider">
                              <ul class="slides">
                                <li><img src="images/templatemo_slide_1.jpg" alt="slide 1" /></li>
                                <li><img src="images/templatemo_slide_2.jpg" alt="slide 2" /></li>
                                <li><img src="images/templatemo_slide_3.jpg" alt="slide 3" /></li>
                              </ul>
                            </div>

        				</div>
                    </div>

                    <article class="row">
						<div class="col col-md-12">
							<img src="images/templatemo_tn_1.jpg" alt="Templatemo Pic 1" class="img-thumbnail img-responsive img_left">
                            <h3>Introduction</h3>
							<p>Botany is free responsive <a href="http://www.tooplate.com" target="_parent">template</a> from <b>templatemo</b> using Bootstrap that can be used for any website. In iaculis lectus vel est luctus, et laoreet dolor scelerisque. Sed a erat nunc. Nam est eros, commodo vitae nisl sed, consectetur dapibus lacus. Ut lectus libero, condimentum quis. Validate <a href="http://validator.w3.org/check?uri=referer" rel="nofollow">XHTML</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow">CSS</a>.
							</p>
							<p><a rel="nofollow" href="http://www.templatemo.com/page/1" class="btn btn-primary" role="button">View More</a></p>
						</div>
					</article>
					
				</div>
			</div>
			<footer class="row credit">
				<div class="col col-md-12">
					<div id="templatemo_footer">
						Copyright Â© 2084 <a href="#">Company Name</a> | Designed by <a rel="nofollow" href="http://www.templatemo.com/preview/templatemo_391_botany">Botany</a>
					</div>
				</div>
			</footer>
		</div>
	</div>

  <!-- jQuery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>

  <!-- FlexSlider -->
  <script defer src="slider/jquery.flexslider.js"></script>

  <script type="text/javascript">
    $(function(){
      SyntaxHighlighter.all();
    });
    $(window).load(function(){
      $('.flexslider').flexslider({
        animation: "slide",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
    });
  </script>

<script type='text/javascript' src='js/logging.js'></script>
</body>
</html>

