<?php
define('HOST','localhost');
define('login','root');
define('pass','');
define('bdd','gestionprojet');
mysql_connect(HOST,login,pass)or die('erreur de connexion');
mysql_select_db(bdd);
//$id_cp='c11';

Zend_Session::start();
$id_equip = new Zend_Session_Namespace('equipe');
 $id_chef = new Zend_Session_Namespace('chef');

$s="SELECT  id_equipe from chef_projet where id_compte='".$id_chef ->id."'";
$r=mysql_query($s)or die(mysql_error());
$d = mysql_fetch_row($r);
$id_equip->id=  $d[0];

$sql="SELECT nom_collaborateur,prenom_collaborateur,fonction_collaborateur FROM collaborateur where collaborateur.id_equipe='".$id_equip->id."'";
$req=mysql_query($sql)or die(mysql_error());
//while ($donnees = mysql_fetch_row($req))
//{echo $donnees[0];
//}
//echo 'id '.$id_equip->id;
?>
<html>
<body><br><br><br>
<center>
	<table border=1>
		<caption>Les membres de l'equipe </caption>
		<tr ALIGN=CENTER>
			<th>Nom </th>
			<th>Prenom</th>
			<th>Fonction  </th>
			
		</tr>
		
			<?php while ($donnees = mysql_fetch_row($req))
		{?>
		<tr ALIGN=CENTER>
			
		
			<td><?php echo $donnees[0];?></td>
			<td><?php echo $donnees[1];?></td>
			<td><?php echo $donnees[2];?></td>
			

			</tr>
		<?php 
		
	}?>
		
	</table></center>
	</body>
</html>