<html>
<body>

    <ul>
    <li><a href="http://localhost/projet/public/chefprojet/accueil" target ="droite">Accueil</li>
</ul>

 <ul>
    <li><a href="http://localhost/projet/public/chefprojet/profilcp" target ="droite">Profil</li>
</ul>

<ul>
    <li><a href="" target ="">Gestion du projet</a></li>
 <ul>  
     <li><a href="http://localhost/projet/public/chefprojet/listerprojet" target ="droite">Lister le projet</a></li>
        <li><a href="http://localhost/projet/public/chefprojet/modifprojet" target="droite">Modifier le projet</a></li>
             <ul>  
                  <li><a href="http://localhost/projet/public/chefprojet/ajouttache" target ="droite">creer une nouvelle tache</a></li>
                   <li><a href="http://localhost/projet/public/chefprojet/modiftache" target="droite">modifier une tache </a></li>
                <li><a href="http://localhost/projet/public/chefprojet/suptache" target="droite">supprimer une tache </a></li>

        
        
 </ul>
        
 </ul>
</ul>
  <ul>
    <li><a href="">Gestion de l'equipe</a></li>
   <ul>  
     <li><a href="http://localhost/projet/public/chefprojet/ajoutmembre" target ="droite">ajouter un membre</a></li>
        <li><a href="http://localhost/projet/public/chefprojet/supmembre" target="droite">supprimer un membre</a></li>
         <li><a href="http://localhost/projet/public/chefprojet/listercollab" target ="droite">Lister les membres  de l'equipe</a></li>
 </ul>
    
 </ul>
   <ul>
     <li><a href="http://localhost/projet/public/authentification/logout">Se deconnecter</a>

     </li></ul>
</body>
</htmL>