<html>
<body>

    <ul><li><a href="http://localhost/projet/public/collab/accueil" target ="droite">Accueil</a></li></ul>

<ul><li><a href="http://localhost/projet/public/collab/profil" target ="droite">Profil</a></li></ul>
 <ul><li><a href="http://localhost/projet/public/collab/consultation" target ="droite">Etat d'avancement du projet</a></li></ul>
 <ul><li><a href="http://localhost/projet/public/collab/matache" target="droite">Ma tache</a></li></ul>
                 
 
   <ul>
     <li><a href="http://localhost/projet/public/authentification/logout">Se deconnecter</a>

     </li></ul>
</body>
</htmL>