<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta name="viewport" content="width=device-width" />
	<title>Botany Services</title>
	<meta name="keywords" content="botany, services, responsive, bootstrap, free template, templatemo" />
	<meta name="description" content="Botany Template, Services, free template, responsive bootstrap" />
	<link href="http://localhost/projet/public/css/font-awesome.min.css" rel="stylesheet">
	<link href="http://localhost/projet/public/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="http://localhost/projet/public/templatemo_style.css" rel="stylesheet" type="text/css">

	<!-- HTML 5 shim for IE backwards compatibility -->
		<!-- [if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
		</script>
		<![endif]-->
	<!--
	Credits
	Equal Height Columns - http://www.hongkiat.com/blog/css-equal-height/
	Font Awesome by Dave Gandy - http://fontawesome.io
-->
</head>
<body class="templatemo_flower_1">
	<div id="main_container">
		<div class="container" id="services">
			<div class="row col-wrap">
				<div id="left_container" class="col col-md-3 col-sm-12">
					<div class="templatemo_logo">
						<a rel="nofollow" href="http://www.templatemo.com/preview/templatemo_391_botany"><img src="http://localhost/projet/public/images/templatemo_logo.png" alt="Botany Theme"></a>
					</div>
					<nav id="main_nav">
						<ul class="nav">
							<li><a href="http://localhost/projet/public/admin/choixprojet"><h6>Gestion des projets </h6></a></li>
							<li><a href="http://localhost/projet/public/admin/choixchef"><h6>Gestion de chef de projet</h6></a></li>
							<li class="active"><a href="#"><h6>Gestion de collaborateurs</h6></a></li>
							<li><a href="contact.html"><h6>Se deconnecter</h6></a></li>
						</ul>
					</nav> <!-- nav -->
					
					
				</div>
				<div id="right_container" class="col col-md-9 col-sm-12">
					<div class="row">
                    	<div class="col col-md-12">
                        	<h2>Service<a href="{{ LINK_HREF }}" title="{{ LINK_TITLE }}" class="right_container_title" rel="{{ LINK_REL }}" target="{{ LINK_TARGET }}">s</a></h2>
                        </div>
                    </div>
					<article class="row">
						<div class="col col-md-12"><h4>Gestion des collaborateurs</h4></div>
						<div class="col col-md-6">
                        	<br/><br/><br/><p>Cras ac elit vel erat aliquet condimentum vitae et libero. Integer gravida fringilla ligula in imperdiet. </p>
							
						</div>
						<div class="col col-md-6">
							<div class="vid_holder">
								<iframe width="400" height="225" src="http://localhost/projet/public/images/gestionprojet.jpg" allowfullscreen></iframe>
							</div>
						</div>
					</article>
					<article class="row">
						<div class="col col-md-4">
							<h4>Ajouter un collaborateur</h4>
							<p class="text-center"><i class="fa fa-smile-o fa-5x"></i></p>
							<p>Proin gravida nibh vel velit auctor aliquet.<a href="http://localhost/projet/public/admin/ajoutcollab" rel="nofollow">continuer</a>.</p>
						</div>
						<div class="col col-md-4">
							<h4>Supprimer un collaborateur</h4>
							<p class="text-center"><i class="fa fa-leaf fa-5x"></i></p>
							<p>Sed non  mauris vitae erat consequat auctor eu in elit. <a href="http://localhost/projet/public/admin/suppcb" rel="nofollow">continuer</a>..</p>
						</div>
						<div class="col col-md-4">
							<h4>Modifier un collaborateur</h4>
							<p class="text-center"><i class="fa fa-camera-retro fa-5x"></i></p>
							<p>Etiam pharetra, erat sed fermentum feugiat.<a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow">continuer</a>..</p>
						</div>
						<div class="col col-md-4">
							<h4>Lister les collaborateurs</h4>
							<p class="text-center"><i class="fa fa-camera-retro fa-5x"></i></p>
							<p>Etiam pharetra, erat sed fermentum feugiat. <a href="http://localhost/projet/public/admin/listcb" rel="nofollow">continuer</a>..</p>
						</div>
					</article>
				</div>
			</div>
			<footer class="row credit">
				<div class="col col-md-12">
					<div id="templatemo_footer">
						Copyright Â© 2084 <a href="#">Company Name</a> | Designed by <a rel="nofollow" href="http://www.templatemo.com/preview/templatemo_391_botany">Botany</a>
					</div>
				</div>
			</footer>
		</div>
	</div>
<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.3.1/jquery.min.js'></script>
<script type='text/javascript' src='http://localhost/projet/public/js/logging.js'></script>
</body>
</html>