
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta name="viewport" content="width=device-width" />
	<title>Botany Template</title>
	<meta name="keywords" content="botany, responsive, bootstrap, free template, fluid layout, templatemo, html css" />
	<meta name="description" content="Botany Template is free responsive template with a fluid background image." />
	<link href="http://localhost/projet/public/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="http://localhost/projet/public/templatemo_style.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="flexslider.css" type="text/css" media="screen" />

	<!-- Modernizr -->
  	<script src="http://localhost/projet/public/slider/modernizr.js"></script>

	<!-- HTML 5 shim for IE backwards compatibility -->
		<!-- [if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
		</script>
		<![endif]-->
	<!--
	Credits
	Equal Height Columns http://www.hongkiat.com/blog/css-equal-height/ -->
</head>
<body class="templatemo_juice_bg">
	<div id="main_container">
		<div class="container" id="home">
			<div class="row col-wrap">
				<div id="left_container" class="col col-md-3 col-sm-12">
                	<div class="templatemo_logo">
						<a rel="nofollow" href="http://www.templatemo.com/preview/templatemo_391_botany"><img src="http://localhost/projet/public/images/templatemo_logo.png" alt="Botany Theme"></a>
					</div>
					<nav id="main_nav">
						<ul class="nav">
							<li class="active"><a href="http://localhost/projet/public/admin/gestion"><h6>Gestion des chefs de projets </h6></a></li><ul>
							<li><a href="#"><h6>Ajouter un chef de projet</h6></a></li>
							<li><a href="http://localhost/projet/public/admin/supprojet"><h6>Supprimer un chef de projet</h6></a></li>
							<li><a href="contact.html"><h6>Modifier un projet</h6></a></li>
							<li><a href="http://localhost/projet/public/admin/listprojet"><h6>Lister les chefs de projet</h6></a></li>
							
						</ul></ul>
						

					</nav> <!-- nav -->
					
				</div>
				<div id="right_container" class="col col-md-9 col-sm-12">

					<div class="row">
                    	<div class="col col-md-12">

                    		<h2>Gestion <a href="http://fr.onlyimage.com" title="images gratuites" class="right_container_title"  target="_blank">de</a> Projets</h2>

                          

        				</div>
                    </div>


<?php
define('HOST','localhost');
define('login','root');
define('pass','');
define('bdd','gestionprojet');
mysql_connect(HOST,login,pass)or die('erreur de connexion');
mysql_select_db(bdd);
$sql='select*from chef_projet';
$req=mysql_query($sql)or die(mysql_error());
//while ($donnees = mysql_fetch_row($req))
//{echo $donnees[0];
//}
?>

<table border=1>
		<caption>Liste des chefs de projet </caption>
		<tr ALIGN=CENTER>
			<th>Nom </th>
			<th>Prenom </th>
			<th>Equipe </th>
			<th>projet affecte </th>
			
		</tr>
		
			<?php while ($donnees = mysql_fetch_row($req))
		{?>
		<tr ALIGN=CENTER>
			
			<td><?php echo $donnees[4];?></td>
			<td><?php echo $donnees[5];?></td>
			<td><?php echo $donnees[2];?></td>
			<td><?php echo $donnees[3];?></td>
			
			</tr>
		<?php }?>
		
	</table>





					
				</div>
			</div>
			<footer class="row credit">
				<div class="col col-md-12">
					<div id="templatemo_footer">
						Copyright Â© 2084 <a href="#">Company Name</a> | Designed by <a rel="nofollow" href="http://www.templatemo.com/preview/templatemo_391_botany">Botany</a>
					</div>
				</div>
			</footer>
		</div>
	</div>

  <!-- jQuery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="http://localhost/projet/public/js/libs/jquery-1.7.min.js">\x3C/script>')</script>

  <!-- FlexSlider -->
  <script defer src="http://localhost/projet/public/slider/jquery.flexslider.js"></script>

  <script type="text/javascript">
    $(function(){
      SyntaxHighlighter.all();
    });
    $(window).load(function(){
      $('.flexslider').flexslider({
        animation: "slide",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
    });
  </script>

<script type='text/javascript' src='http://localhost/projet/public/js/logging.js'></script>
</body>
</html>










