<html>
<body>

    <ul>
    <li><a href="http://localhost/projet/public/admin/accueil" target ="droite">Accueil</li>
</ul>

<ul>
    <li><a href="http://localhost/projet/public/admin/gestion" target ="droite">Gestion de Projets</a></li>
    <ul>
        <li><a href="http://localhost/projet/public/admin/principal" target ="droite">Ajouter un projet</a></li>
        <li><a href="http://localhost/projet/public/admin/modifprojet" target="droite">Modifier un projet</a></li>
        <li><a href="http://localhost/projet/public/admin/supprojet" target="droite">Supprimer un projet</a></li>
        <li><a href="http://localhost/projet/public/admin/listprojet" target="droite">Afficher la liste des projets</a></li>
    </ul></li>
    <li><a href="http://localhost/projet/public/admin/gestionchef" target ="droite">Gestion des Chef des projets</a></li>
    <ul> 
        <li><a href="http://localhost/projet/public/admin/ajoutchef" target ="droite">Ajouter un chef de projet</li></a></li>
        <li><a href="http://localhost/projet/public/admin/modifcp" target ="droite">Modifier un chef de projet</li></a>
		<li><a href="http://localhost/projet/public/admin/suppcp" target ="droite">Supprimer un chef de projet</li></a>
		<li><a href="http://localhost/projet/public/admin/listcp" target="droite">Afficher la liste des  chef de projets</li></a>
    </ul></li>
	  <li><a href="http://localhost/projet/public/admin/gestioncb" target ="droite">Gestion des Collaborateurs</a></li>
    <ul> 
        <li><a href="http://localhost/projet/public/admin/ajoutcollab" target ="droite">Ajouter des collaborateur</a></li>
        <li><a href="http://localhost/projet/public/admin/modifcb" target ="droite">Modifier un Collaborateur</a></li>
        <li><a href="http://localhost/projet/public/admin/suppcb" target ="droite">Supprimer un Collaborateur</a></li>
        <li><a href="http://localhost/projet/public/admin/listcb" target ="droite">Afficher la liste des Collaborateurs</a></li>
    </ul></li>
     <li><a href="http://localhost/projet/public/authentification/logout" target ="droite">Se deconnecter</a>

     </li>
</body>
</htmL>